# Generated by Django 3.2.6 on 2021-08-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProhibitedGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('replace', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
